spring:
  datasource:
    hikari:
      # write host
      primary:
        jdbc-url: jdbc:mysql://localhost:3306/template?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
      # read host
      secondary:
        jdbc-url: jdbc:mysql://localhost:3307/bulk?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
